### ISSUE TITLE
Some considerations about Wild Shape 

### ISSUE THREAD

**Issue by Marcloure** [mlenser/tabletop-homebrew-issues#25]
I am opening a new issue for this, since the other one is already close and done.

While I very much like this new way to handle Wild Shape, I have a concern about it. Mainly that you can't exactly build around Wild Shape as you could in the past.

When you change shape, you lose all your proficiency bonuses and, more important, you lose all your Feats. This means you can't pick Feats to improve your shaped form, like Icon of Deception, Stalker's Prowess, Ambush, etc. Losing proficiency also means you lose any knowledge you might have through Lore skills.

Do you think this is an issue? Or do you think that when a character wild shapes, it's now that beast through and through?

Lastly, I also have a suggestion. Maybe there could be a Feat that allows you to keep your feats and class features while Wild Shaped? I'm not sure how good that is to the game, though.

**Comment by mlenser** [comment]
> When you change shape, you lose all your proficiency bonuses and, more important, you lose all your Feats.

Feats are not meant to go away. I'll fix that.

Proficiency bonuses are kept for saves and skills and attack is done via spell DC so that should all be fine. Unless I missed something?

> Losing proficiency also means you lose any knowledge you might have through Lore skills.

You don't lose proficiencies:
"You also retain all of your skill and saving throw proficiencies, in addition to gaining those of the creature. If the creature has the same proficiency as you and the bonus in its stat block is higher than yours, use the creature’s bonus instead of yours."


> Maybe there could be a Feat that allows you to keep your feats and class features while Wild Shaped

Class features are already kept:
"You retain the benefit of any features from your class, race, or other source and can use them if the new form is physically capable of doing so."

**Comment by mlenser** [comment]
Added feats:
"You retain the benefit of any **_feats and_** features from your class, race, or other source and can use them if the new form is physically capable of doing so."

**Comment by Marcloure** [comment]
Now, I have another question. Do you keep your Stamina Dice limit or the beast's limit? Since you keep your features, you should keep your limit as well, but you also gain the maneuvers known by the form?

**Comment by mlenser** [comment]
- You retain your stamina dice and dice limit and can use your new form’s stamina dice.
- You can use any maneuver you know or a maneuver known by your new form, but you can’t cast spells
